views/course_index.py
from flask import Flask, render_template, redirect, request, flash, g, url_for, session, abort, Blueprint
import uuid
import sqlite3
import requests
import datetime
from mangopay_globals import get_db

''' Course - Index, create, and edit '''

course_index = Blueprint('course_index', __name__)

''' Indexing and Creation '''
@course_index.route('/courses', methods=['GET', 'POST'])
def courses():
	if 'username' in session:
		db = get_db()
		if request.method == 'GET':
			uid = uuid.uuid4()

			''' The following query shows all courses that has 
				events or locations associated to it.
			''' 
			cur_courses = db.execute('SELECT tmp_course.*, \
			tmp_location.location, tmp_event.date FROM tmp_event \
			INNER JOIN tmp_course ON tmp_course.course_id = tmp_event.course_id \
			INNER JOIN tmp_location ON tmp_event.location_id = tmp_location.location_id \
			GROUP BY tmp_course.course_uid')
			courses = cur_courses.fetchall()
			cur_locations = db.execute('SELECT * FROM tmp_location')
			locations = cur_locations.fetchall()

			''' The following query shows the rest of the courses
				that are orphaned without any events or locations.
			'''
			cur_orphaned_courses = db.execute('SELECT tmp_course.* FROM tmp_course \
			WHERE NOT EXISTS (SELECT tmp_event.course_id FROM tmp_event \
			WHERE tmp_course.course_id = tmp_event.course_id)')
			orphaned_courses = cur_orphaned_courses.fetchall()
			return render_template('course-index.html', courses=courses, 
				orphaned_courses=orphaned_courses, locations=locations, uid=uid)
		elif request.method == 'POST':
			course_uid = request.form['course_uid']
			title = request.form['course_name']
			online_fees = request.form['online_fees']
			offline_fees = request.form['offline_fees']
			locations = request.form.getlist('location')
			db.execute('INSERT INTO tmp_course (course_uid, title, online_fees, offline_fees) \
				VALUES (?, ?, ?, ?)', [course_uid, title, online_fees, offline_fees])
			cur_course_id = db.execute('SELECT course_id FROM tmp_course WHERE course_uid=?', [course_uid])
			course_id = cur_course_id.fetchone()[0]
			for location_id in locations:
				db.execute('INSERT INTO tmp_event (course_id, location_id) \
					VALUES (?, ?)', [course_id, location_id])
			db.commit()
			flash("Course successfully created. Please add a new event to the course below.", "success info")
			return redirect(url_for('event_index.events', course_id=course_id))
	else:
		return render_template('login.html')

''' Edit '''
@course_index.route('/course/<uid>/edit', methods=['GET', 'POST'])
def edit_course(uid):
	if 'username' in session:
		db = get_db()
		cur_course_id = db.execute('SELECT course_id FROM tmp_course WHERE course_uid=?', [uid])
		course_id = cur_course_id.fetchone()[0]
		if request.method == 'GET':
			cur_course = db.execute('SELECT tmp_course.*, \
			tmp_location.location FROM tmp_event \
			INNER JOIN tmp_course ON tmp_course.course_id = tmp_event.course_id \
			INNER JOIN tmp_location ON tmp_event.location_id = tmp_location.location_id \
			WHERE tmp_course.course_uid = ?', [uid])
			course = cur_course.fetchall()[0]
			return render_template('course-edit.html', course=course)

		elif request.method == 'POST':
			title = request.form['course_name']
			online_fees = request.form['online_fees']
			offline_fees = request.form['offline_fees']
			camp_total_online_fees = request.form['camp_total_online_fees']
			db.execute('UPDATE tmp_course SET title = ?, online_fees = ?, \
				offline_fees = ?, camp_total_online_fees = ? \
				WHERE course_uid = ?', [title, online_fees, offline_fees, camp_total_online_fees, uid])
			db.commit()
			flash("Successfully edited the course.", "success")
			return redirect(url_for('course_index.edit_course', uid=uid))
	else:
		return render_template('login.html')

@course_index.route('/orphan-course/<uid>/edit', methods=['GET', 'POST'])
def edit_course_orphan(uid):
	if 'username' in session:
		db = get_db()
		cur_course_id = db.execute('SELECT course_id FROM tmp_course WHERE course_uid=?', [uid])
		course_id = cur_course_id.fetchone()[0]
		if request.method == 'GET':
			cur_course = db.execute('SELECT * FROM tmp_course \
			WHERE course_uid = ?', [uid])
			course = cur_course.fetchone()
			return render_template('course-edit-orphan.html', course=course)

		elif request.method == 'POST':
			title = request.form['course_name']
			online_fees = request.form['online_fees']
			offline_fees = request.form['offline_fees']
			camp_total_online_fees = request.form['camp_total_online_fees']
			db.execute('UPDATE tmp_course SET title = ?, online_fees = ?, \
				offline_fees = ?, camp_total_online_fees = ? \
				WHERE course_uid = ?', [title, online_fees, offline_fees, camp_total_online_fees, uid])
			db.commit()
			flash("Successfully edited the course.", "success")
			return redirect(url_for('course_index.edit_course_orphan', uid=uid))
	else:
		return render_template('login.html')

''' Registration Link '''
@course_index.route('/<course_name>/<course_uid>/registration-link', methods=['GET'])
def generate_registration_link(course_name, course_uid):
	if 'username' in session:
		registration_link = '<a class="registration button" id="mango_registration_payment" target="_blank" href="{}?course_uid={}">Register</a>'.format(request.url_root, course_uid)
		just_the_registration_link = '{}?course_uid={}'.format(request.url_root, course_uid)
		return render_template('registration-link.html', registration_link=registration_link, 
			just_the_registration_link=just_the_registration_link, course_name=course_name)
	else:
		return render_template('login.html')

views/dashboard.py
from flask import Flask, render_template, redirect, request, flash, g, url_for, session, abort, Blueprint
import requests
import sqlite3
from mangopay_globals import msg91_key, get_db

''' Administration '''

admin_dashboard = Blueprint('dashboard', __name__)

@admin_dashboard.route('/dashboard', methods=['GET'])
def dashboard():
	if 'username' in session:
		''' Counters '''
		counters = {}

		db = get_db()
		counters['course'] = db.execute('SELECT Count(*) FROM tmp_course').fetchone()[0]
		counters['event'] = db.execute('SELECT Count(*) FROM tmp_event').fetchone()[0]
		counters['registration'] = db.execute('SELECT Count(*) FROM tmp_parent_registration').fetchone()[0]
		counters['location'] = db.execute('SELECT Count(*) FROM tmp_location').fetchone()[0]

		''' APIs '''
		# MSG91
		try:
			msg91_url = "https://control.msg91.com/api/balance.php?authkey={}&type=1".format(msg91_key)
			message_balance = requests.get(msg91_url).text
		except:
			message_balance = "API Error"

		# XKCD
		try:
			xkcd_url = "https://xkcd.com/info.0.json"
			xkcd = requests.get(xkcd_url).json()
		except:
			xkcd = None

		# Design Quotes
		try:
			quotes_url = "https://quotesondesign.com/wp-json/posts?filter[orderby]=rand&filter[posts_per_page]=1"
			quote = requests.get(quotes_url).json()
			print quote
		except:
			quote = None 

		return render_template('dashboard.html', message_balance=message_balance, xkcd=xkcd, 
			themango_posts=themango_posts, quote=quote, counters=counters)
	else:
		return render_template('login.html')

views/event_index.py
from flask import Flask, render_template, redirect, request, flash, g, url_for, session, abort, Blueprint
import uuid
import sqlite3
import requests
import datetime
from mangopay_globals import get_db

event_index = Blueprint('event_index', __name__)

@event_index.route('/<course_id>/event', methods=['GET', 'POST'])
def events(course_id):
	if 'username' in session:
		db = get_db()
		if request.method == 'GET':
			cur_locations = db.execute('SELECT location_id, location FROM tmp_location')
			locations = cur_locations.fetchall()
			cur_events = db.execute('SELECT tmp_event.event_id, tmp_course.title, \
			tmp_location.location, tmp_event.date FROM tmp_event \
			INNER JOIN tmp_course ON tmp_course.course_id = tmp_event.course_id \
			INNER JOIN tmp_location ON tmp_location.location_id = tmp_event.location_id \
			WHERE tmp_event.course_id = ?', [course_id])
			events = cur_events.fetchall()
			cur_course_info = db.execute('SELECT course_uid, title FROM tmp_course WHERE \
			course_id=?', [course_id])
			for course_uid, course_title in cur_course_info.fetchall():
				course_uid = course_uid
				course_title = course_title
			return render_template('event-index.html', events=events,
					course_id=course_id, locations=locations, 
					course_title=course_title, course_uid=course_uid)
		elif request.method == 'POST':
			date = request.form['date']
			location_id = request.form['location']
			try:
				db.execute('INSERT INTO tmp_event (location_id, course_id, date) \
					VALUES (?, ?, ?)', [location_id, course_id, date])
				db.commit()
				flash("Event successfully added!", "success")
			except sqlite3.IntegrityError as e:
				flash("Event exists already!", "error")
			return redirect(url_for('event_index.events', course_id=course_id))
	else:
		return render_template('login.html')
@event_index.route('/event/<event_id>/edit', methods=['GET', 'POST'])
def edit_event(event_id):
	if 'username' in session:
		db = get_db()
		if request.method == 'GET':
			cur_events = db.execute('SELECT tmp_event.event_id, tmp_course.course_id, \
			tmp_course.title, tmp_location.location, tmp_event.date \
			FROM tmp_event INNER JOIN tmp_course ON tmp_course.course_id = tmp_event.course_id \
			INNER JOIN tmp_location ON tmp_location.location_id = tmp_event.location_id \
			WHERE tmp_event.event_id = ?', [event_id])
			event = cur_events.fetchone()
			cur_locations = db.execute('SELECT * FROM tmp_location')
			locations = cur_locations.fetchall()
			return render_template('event-edit.html', event=event, locations=locations)
		elif request.method == 'POST':
			try:
				date = request.form['date']
				location_id = request.form['location']
				course_id = request.form['course_id']
				db.execute('UPDATE tmp_event SET location_id = ?, date = ? \
				WHERE event_id = ?', [location_id, date, event_id])
				db.commit()
				flash('Event updated!', "success")
			except sqlite3.IntegrityError:
				flash('Event already exists!', "error")
			return redirect(url_for('event_index.events', course_id=course_id))
	else:
		return render_template('login.html')

@event_index.route('/event/<event_id>/confirm-delete', methods=['GET'])
def confirm_delete_event(event_id):
	if 'username' in session:
		db = get_db()
		if request.method == 'GET':
			cur_course_id = db.execute('SELECT course_id FROM tmp_event \
			WHERE event_id=?',[event_id])
			course_id = cur_course_id.fetchone()[0]
			flash('Are you sure you want to delete? This will \
			also affect the previous registrations associated with this event. \
			It is recommended to ignore this event for archival purposes. \
			If you had just created the event and no registrations have been done, \
			you may delete it.', "warning")
			return render_template('event-delete-confirm.html', event_id=event_id, 
				course_id=course_id)
	else:
		return render_template('login.html')

@event_index.route('/event/<event_id>/delete', methods=['POST'])
def delete_event(event_id):
	if 'username' in session:
		db = get_db()
		if request.method == 'POST':
			course_id = request.form['course_id']
			db.execute('DELETE FROM tmp_event WHERE event_id=?', [event_id])
			flash('Event deleted successfully.', "success")
			db.commit()
			return redirect(url_for('event_index.events', course_id=course_id))
	else:
		return render_template('login.html')

views/index.py
from flask import Flask, render_template, redirect, request, flash, g, url_for, session, abort, Blueprint
import uuid
import sqlite3
import requests
import datetime
from mangopay_globals import get_db

''' Index '''

index = Blueprint('index', __name__)

@index.route('/')
def app_create():
	if request.args.get('course_uid'):
		course_uid = request.args.get('course_uid')
		parent_uid = uuid.uuid4()
		db = get_db()
		cur_payment = db.execute('SELECT course_uid, title, online_fees, \
			offline_fees, course_id, camp_total_online_fees \
			FROM tmp_course WHERE course_uid=?', [course_uid])
		try:
			course = cur_payment.fetchone()
			if isinstance(course[5], (int, long)) or (course[5] is None):
				cur_locations = db.execute('SELECT tmp_event.event_id,  \
				tmp_location.location, tmp_event.date FROM tmp_location \
				INNER JOIN tmp_event ON tmp_event.location_id = tmp_location.location_id \
				WHERE tmp_event.course_id = ?', [course[4]])
				all_locations = cur_locations.fetchall()
				valid_locations = {}
				''' This loops over the location data to do a date comparison
					to automatically remove the locations where events were expired.
					This also closes the registrations automatically.
				'''
				for location in all_locations:
					course_date = datetime.datetime.strptime(location[2], '%Y-%m-%d').date()
					current_date = datetime.date.today()
					if current_date >= course_date:
						valid_locations[location] = 'expired'
					else:
						valid_locations[location] = 'in progress'
			else:
				flash("TOF default not set.", "error_text")
				abort(500)

		except (IndexError, TypeError) as e:
			flash("This is not a valid course ID.\
				Sorry for the missing link. It's out there somewhere! \
				We'll get it soon. Try again later. Okay? Fine? Cool! \
				Now, if you are an admin, please locate or create the course. \
				If the course exists, please associate an event to it.", "warning")
			abort(404)
			course = None
			valid_locations = None
		return render_template('app.html', course=course, locations=valid_locations, 
			parent_uid=parent_uid)
		
	else:
		abort(404)

views/location_index.py
from flask import Flask, render_template, redirect, request, flash, g, url_for, session, abort, Blueprint
import uuid
import sqlite3
import requests
import datetime
from mangopay_globals import get_db

location_index = Blueprint('location_index', __name__)

''' Location index '''
@location_index.route('/locations', methods=['GET', 'POST'])

def locations():
	if 'username' in session:
		db = get_db()
		if request.method == 'GET':
			cur_locations = db.execute('SELECT location_id, location FROM tmp_location')
			locations = cur_locations.fetchall()
			return render_template('course-locations.html', locations=locations)
		elif request.method == 'POST':
			try:
				location = request.form['course-location']
				db.execute('INSERT INTO tmp_location (location) VALUES (?)', [location])
				db.commit()
			except sqlite3.IntegrityError:
				flash('Location already exists!',"error")
			return redirect(url_for('locations'))
	else:
		return render_template('login.html')

views/registration_index.py
from flask import Flask, render_template, redirect, request, flash, g, url_for, session, abort, Blueprint
import uuid
import sqlite3
import requests
import datetime
from mangopay_globals import get_db

''' Registration - Index and single'''

registration_index = Blueprint('registration_index', __name__)

@registration_index.route('/registrations', methods=['GET'])
def registrations():
	if 'username' in session:
		db = get_db()
		if request.method == 'GET':
			cur_parents = db.execute('SELECT tmp_parent_registration.*, \
			tmp_course.title, tmp_location.location, tmp_event.date FROM tmp_parent_registration \
			INNER JOIN tmp_course ON tmp_course.course_id = tmp_parent_registration.course_id \
			INNER JOIN tmp_location ON tmp_location.location_id = tmp_event.location_id \
			INNER JOIN tmp_event ON tmp_event.event_id = tmp_parent_registration.event_id')
			parents = cur_parents.fetchall()
			return render_template('registration-index.html', parents=parents)
	else:
		return render_template('login.html')

@registration_index.route('/registrations/<course_uid>/<course_name>', methods=['GET'])
def registrations_single(course_uid, course_name):
	if 'username' in session:
		db = get_db()
		if request.method == 'GET':
			cur_course_id = db.execute('SELECT course_id FROM tmp_course WHERE course_uid=?', [course_uid])
			course_id = cur_course_id.fetchone()[0]
			cur_parents = db.execute('SELECT tmp_parent_registration.*, tmp_course.title, \
			tmp_location.location FROM tmp_parent_registration \
			INNER JOIN tmp_course ON tmp_course.course_id = tmp_parent_registration.course_id \
			INNER JOIN tmp_location ON tmp_location.location_id = tmp_event.location_id \
			INNER JOIN tmp_event ON tmp_event.event_id = tmp_parent_registration.event_id \
			WHERE tmp_parent_registration.course_id = ?', [course_id])
			parents = cur_parents.fetchall()

			return render_template('registration-index-single.html', parents=parents, course_name=course_name)
	else:
		return render_template('login.html')

@registration_index.route('/registrations/<course_uid>/<event_id>/<course_name>', methods=['GET'])
def registrations_single_event(course_uid, event_id, course_name):
	if 'username' in session:
		db = get_db()
		if request.method == 'GET':
			cur_course_id = db.execute('SELECT course_id FROM tmp_course WHERE course_uid=?', [course_uid])
			course_id = cur_course_id.fetchone()[0]
			cur_parents = db.execute('SELECT tmp_parent_registration.*, tmp_course.title, \
			tmp_location.location, tmp_event.date FROM tmp_parent_registration \
			INNER JOIN tmp_course ON tmp_course.course_id = tmp_parent_registration.course_id \
			INNER JOIN tmp_location ON tmp_location.location_id = tmp_event.location_id \
			INNER JOIN tmp_event ON tmp_event.event_id = tmp_parent_registration.event_id \
			WHERE tmp_parent_registration.course_id = ? AND tmp_event.event_id = ?', [course_id, event_id])
			parents = cur_parents.fetchall()
			event_date_cur = db.execute('SELECT date FROM tmp_event WHERE event_id=?', [event_id])
			event_date = event_date_cur.fetchone()[0]
			return render_template('registration-index-single-event.html', parents=parents, course_name=course_name, event_date=event_date)
	else:
		return render_template('login.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/normalize.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='media/favicon.png') }}"/>
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    <title>
        {% block title %}{% endblock %} – Mango Registrations and Payments
    </title>
    {% endblock %}
</head>
{% set navigation_bar = [
    ('/dashboard', 'dashboard', 'Dashboard'),
    ('/courses', 'courses', 'Courses'),
    ('/registrations', 'registrations', 'Registrations'),
    ('/logout', 'logout', 'Logout')
] -%}
{% set active_page = active_page|default('index') -%}
<body>
<main>
    <header>
        <div class="navbar">
            <div class="navbar-content">
                <ul>
                    <li id = "logo"><a href="{{ url_for('dashboard.dashboard') }}"><img src="{{ url_for('static', filename='media/mango-logo.png') }}" title="Mango Payments"></a></li>
                </ul>
                {% if session['username'] %}
                <ul id="navigation">
                    {% for href, id, caption in navigation_bar %}
                      <li {% if id == active_page %} class="active"{% endif%}><a href="{{ href|e }}">{{ caption|e }}</a></li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
        <div class="header">
            <div class="header-content">        
                {% block header %}
                {% endblock %}
            </div>
        </div>
    </header>
    <!-- Content Begins -->
    <div class = container id="content">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul class=flashes>
                    {% for category, message in messages %}
                        <li class="{{ category }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
    </div>
    <!-- Content Ends -->
</main>
<!-- Footer -->
<footer>
    <p class="mangopay-info">Mango Pay 1.2.0</p>
    <p class="footer-links"><a href="https://themango.co/about">About</a>&nbsp;&nbsp;&nbsp;<a href="https://themango.co/privacy">Privacy</a>&nbsp;&nbsp;&nbsp;<a href="https://themango.co/#mango-contact-section">Contact</a>&nbsp;&nbsp;&nbsp;<a href="https://themango.co/disclaimer">Disclaimer</a>&nbsp;&nbsp;&nbsp;<a href="https://themango.co/terms">Terms</a>&nbsp;&nbsp;&nbsp;<a href="https://themango.co/refund-policy">Refund Policy</a></p>
</footer>
<!-- Scripts -->
</body>

</html>

templates/confirmation.html
{% extends "base.html" %}

{% block title %}Response{% endblock %}

{% block header %}
    <span class="title-header centered">Response</span><span class="subtitle-header centered">Payment response message</span>
{% endblock %}

{% block content %}
	<div class="centered center" style="margin-bottom: 1.5em;"><a class="button-primary" href="{{ url_for('index.app_create', course_uid=course_uid) }}">New Registration</a></div>
	<div class="info-line centered">
		<p class="info-line centered center">For further qeuries, contact us through email or phone.</br>support@themango.co | +91-9952243541</p>
	</div>
{% endblock %}

templates/course-index.html
{% extends "base.html" %}

{% set active_page = "courses" %}

{% block title %}Course Index{% endblock %}

{% block header %}
    <span class="title-header">Course Index</span><span class="subtitle-header">Click <a href="#new-course">here</a> to add new course</span>
    {% include 'datatable-resources.html' %}
{% endblock %}

{% block content %}

    <!-- Valid Courses -->
    <section>
        <h2>Live Courses</h2>
        <p class="info-line">To validate courses, associate it with an event before linking at themango.co.</p>
        <script type="text/javascript">
        $(document).ready(function() {
            $('#courses').DataTable( {
                dom: 'Bfrtip',
                buttons: [
                    'copyHtml5',
                    'excelHtml5',
                ]
            } );
        } );
        </script>
        <table id="courses" class="display" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Course Name</th>
            <th>Online Fees</th>
            <th>Offline Fees</th>
            <th>Full Online Fee (Camps only)</th>
            <th>Events</th>
            <th>Edit</th>
            <th>Registrations</th>
            <th>Registration Link</th>
        </tr>
        </thead>
        <tbody>
        {% for course in courses %}
        <tr>
            {% if course[8] %}
                <td>{{ course[2] }}</td>
            {% else %}
                <td>{{ course[2] }} | <a href="{{ url_for('event_index.events', course_id=course[0]) }}">View Event</a></td>
            {% endif %}
            <td>{{ course[3] }}</td>
            <td>{{ course[4] }}</td>
            <td>{{ course[6] }}</td>
            <td><a href="{{ url_for('event_index.events', course_id=course[0]) }}">View</a></td>
            <td><a href="{{ url_for('course_index.edit_course', uid=course[1]) }}">Edit</a></td>
            <td><a href="{{ url_for('registration_index.registrations_single', course_uid=course[1], course_name=course[2]) }}">View Registrations</a></td>
            <td><a href="{{ url_for('course_index.generate_registration_link', course_name=course[2], course_uid=course[1]) }}">Generate Registration Link</a></td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
    </section>

    <!-- Oprhaned Courses -->
    <section>
        <h2>Orphaned Courses</h2>
        <p class="info-line">The following courses do not have any locations or dates associated with them. Ignore if they are not used, or add an event.</p>
        <script type="text/javascript">
        $(document).ready(function() {
            $('#orphaned-courses').DataTable( {
                dom: 'Bfrtip',
                buttons: [
                    'copyHtml5',
                    'excelHtml5',
                ]
            } );
        } );
        </script>
        <table id="orphaned-courses" class="display" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Course Name</th>
            <th>Online Fees</th>
            <th>Offline Fees</th>
            <th>Full Online Fees (Camps only)</th>
            <th>Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for course in orphaned_courses %}
        <tr>
            {% if course[8] %}
                <td>{{ course[2] }}</td>
            {% else %}
                <td>{{ course[2] }} | <a href="{{ url_for('event_index.events', course_id=course[0]) }}">Add Event</a></td>
            {% endif %}
            <td>{{ course[3] }}</td>
            <td>{{ course[4] }}</td>
            <td>{{ course[6] }}</td>
            <td><a href="{{ url_for('course_index.edit_course_orphan', uid=course[1]) }}">Edit</a></td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
    </section>

    <!-- Add New Course -->
    <section>
        <h2 id="new-course">Add New Course</h2>
        <p class="info-line">You can add multiple locations by clicking control key. The event dates can be added once the course has been created.</p>
        <form action="{{ url_for('course_index.courses') }}" method="POST">
            <input type="hidden" name="course_uid" id="course_uid" value="{{ uid }}" readonly></br>
            <input type="text" name="course_name" id="course_name" value="" placeholder="Course Name" required></br>
            <input type="number" name="online_fees" id="online_fees" value="" placeholder="Course Online Fees" required></br>
            <input type="number" name="offline_fees" id="offline_fees" value="" placeholder="Course Offline Fees" required></br>
            <select multiple name="location" id="location" style="height: auto;">
                {% for location in locations %}
                <option value="{{ location[0] }}">{{ location[1] }}</option>
                {% endfor %}
            </select></br>
            <input type="submit" class="button-primary" name="submit" value="Add Course">
        </form>
    </section>
{% endblock %}

templates/event-index.html
{% extends "base.html" %}

{% block title %}Events Index for {{ course_title }} {% endblock %}

{% block header %}
    <span class="title-header">{{ course_title }} Events</span><span class="subtitle-header">All events so far</span>
    {% include 'datatable-resources.html' %}
{% endblock %}

{% block content %}
    <script type="text/javascript">
    $(document).ready(function() {
        $('#course-events-all').DataTable( {
            dom: 'Bfrtip',
            order: [[1, 'desc']],
            buttons: [
                'copyHtml5',
                'excelHtml5',
            ]
        } );
    } );
    </script>
    <table id="course-events-all" class="display" cellspacing="0" width="100%">
    <thead>  
    <tr>
        <th>Location</th>
        <th>Date</th>
        <th>View Registrations</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% if events %}
        {% for event in events %}
            <tr>
                <td>{{ event[2] }}</td>
                {% if event[3] == None %}
                    <td><a href="{{ url_for('event_index.edit_event', event_id=event[0]) }}">Add Date</a></td>
                {% else %}    
                    <td>{{ event[3]|datetimeformat('%B %d, %Y - %A') }}</td>
                {% endif %}
                <td><a href="{{ url_for('registration_index.registrations_single_event', course_uid=course_uid, event_id=event[0], course_name=course_title) }}">View Registrations</a></td>
                <td><a href="{{ url_for('event_index.edit_event', event_id=event[0]) }}">Edit</a></td>
                <td><a href="{{ url_for('event_index.confirm_delete_event', event_id=event[0]) }}">Delete</a></td>
            </tr>
        {% endfor %}
    {% endif %}
    </tbody>
    </table>
    <form action="{{ url_for('event_index.events', course_id=course_id) }}" method="POST">
        <input required type="date" name="date" id="date" value="">
        <select name="location" id="location">
            {% for location in locations %}
                <option value="{{ location[0] }}">{{ location[1] }}</option>
            {% endfor %}
        </select>
        <input type="submit" class="button-primary" name="submit" value="Add Event">
    </form>
{% endblock %}